## Optional Tools ##

fastqc: True
meqc: True
icov: True 

## Files Paths ##

## Path of the samples
samples:
  #dicitura: nome: path/to/nome (nel path avrà formato "nome_unit.fastq.gz")
  #pensare a includere L001 nelle units


## Path of the reference genome
reference: ""

## Path of the bed file 
bed: ""

## Path of the filtered genome file 
filtered: "" #cerca hg19_ucsc_filtered_genomeFile.txt

## Path of the reference genome dictionary
dict: ""

## Path to the Snpeff database
snpeff: ""  

## Path to the dbNSFP database
dbnsfp: ""

## Path to the dbNSP database
dbsnp: ""


## Extra Softwares Paths ##

java_path: ""
snpsift_path: ""

## Tools Parameters ##

# The java_opts param allows for additional arguments to be passed to the java compiler,
# e.g. “-Xmx4G” for one, and “-Xmx4G -XX:ParallelGCThreads=10” for two options.

# The extra param alllows for additional program arguments.

# For more information see, https://software.broadinstitute.org/gatk/documentation/article?id=11050

FastQC:
  params: ""

bwaMem:
  params:
    sort: "samtools" # Can be 'none', 'samtools' or 'picard'.
    sort_order: "coordinate"  # Can be 'queryname' or 'coordinate'.
    sort_extra:  "" # Extra args for samtools/picard.

picard_AddOrReplaceGroups:
  params: ""

# the bed file path must be hard coded
samtools_View:
  params: ""

picard_MarkDuplicates:
  params: ""

gatk_BaseRecalibrator:
  params:
    extra: "" 
    java_opts: "" 

gatk_ApplyBQSR:
  params:
    extra: ""  
    java_opts: ""  

picard_Sortsam:
  params:
    sort_order: ""
    extra: ""

samtools_Index: 
  params: "" 

gatk_HaplotypeCaller:
  params:
    java_opts: "" 
    extra: ""

gatk_CombineGvcfs:
  params:
    extra: "" 
    java_opts: "" 

gatk_GenotypeGvcfs:
  params:
    extra: "" 
    java_opts: "" 

gatk_SelectVariants:
  snps:
    extra: ""
  indel:
    extra: ""

gatk_FilterVariants:
  snps:
    filters: {""}
  indels:
    filters: {""}

#snpeff_Annotate:
#   params:
#     extra: ""
#     java_opts: "" 

snpsift_Annotate:
  params:
    java_opts: ""
    extra: ""

snpsift_VarType:
  params:
    java_opts: ""
    extra: ""

snpsift_dbNSFP:
  params:
    java_opts: ""
    extra: "-n " # -n annota tutti i fields tranne quelli specificati con -f, -g versione del genoma

extractFields:
  path: ""

  


